apiVersion: apps/v1
kind: Deployment
metadata:
  name: categories-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: categories-service
  template:
    metadata:
      labels:
        app: categories-service
    spec:
      containers:
      - name: categories-service
        image: 401704305923.dkr.ecr.ap-southeast-2.amazonaws.com/categories-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        # Add more environment variables if needed (e.g., DB credentials)

---
apiVersion: v1
kind: Service
metadata:
  name: ClusterIP 
spec:
  type: LoadBalancer
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: categories-service
